name: Winget and Nuget package publish

on:
  release:
    types: [published]

env:
   PACKAGE_NAME_REGEX: .+win-x64.+\.msi
   PACKAGE_ID: PTRTECH.UVtools
   WINGET_TOKEN: ${{ secrets.WINGET_TOKEN }}
   NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
   
jobs:

  winget:
    name: Winget - Pull request
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Download WingetCreate.exe
        run: iwr -Uri https://aka.ms/wingetcreate/latest -OutFile wingetcreate.exe
      - name: Set VERSION variable from tag
        run: | 
          $version = $github.event.release.tag_name.Replace('v', '')
          if($version.Length -lt 5)
          { 
             Write-Error "Version $version is too short!"
             exit -1 
          }
          Write-Output "Version: ${version}"
          "VERSION=${version}" >> $env:GITHUB_ENV
      - name: Set VERSION variable from tag
        run: | 
          $installerUrl = $github.event.release.assets | Where-Object -Property name -match "${PACKAGE_NAME_REGEX}" | Select -ExpandProperty browser_download_url -First 1
          if($null -eq $installerUrl)
          { 
             Write-Error "Installer URL not found on ${github.event.release.assets}"
             exit -1 
          }
          Write-Output "Installer url: ${installerUrl}"
          "INSTALLER_URL=${installerUrl}" >> $env:GITHUB_ENV
      - name: Submit package to Windows Package Manager Community Repository
        run: .\wingetcreate.exe update ${PACKAGE_ID} --version ${VERSION} --urls ${INSTALLER_URL} --token ${WINGET_TOKEN} --submit
        
  nuget:
    name: Nuget - Publish package
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Verify commit exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master
      - name: Set VERSION variable from tag
        run: | 
          VERSION=${{ github.event.release.tag_name }}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV
      - name: Build
        run: dotnet build --configuration Release
      - name: Pack
        run: dotnet pack UVtools.Core --configuration Release --no-build --output .
      - name: Push nuget.org
        run: dotnet nuget push UVtools.Core.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
